apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  serviceName: "result"
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result:before
        name: result
        ports:
        - containerPort: 80
          name: result
