apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  serviceName: "vote"
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote:before
        name: vote
        ports:
        - containerPort: 80
          name: vote
